server:
  port: 9000
jwt:
  TOKEN_EXPIRED: 360000
  SECRET: secretno
  TOKEN_PREFIX: Bearer
  HEADER_STRING: Authorization
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/neat
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect