server:
  port: 9000
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/neat
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  resources:
    static-locations: /home/victor/IdeaProjects/neatvue/public
  jpa:
    generate-ddl: false
    open-in-view: true
    properties:
      hibernate:
        ddl-auto: validate
        jdbc:
          lob:
            non_contextual_creation: true
      database-platform: org.hibernate.dialect.PostgreSQL11Dialect
    show-sql: false
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: 1512
# App Properties
app:
  project:
    restrictions:
      max_allowed_neat_config: 5
  jwt:
    secret: SECRET
    access:
      expiration: 864000
      header: Authorization
      prefix: Bearer_
    refresh:
      expiration: 2592000000

loger:
  level:
    root: DEBUG


path:
  avatars: /home/victor/IdeaProjects/neatvue/public/avatars
  projects:
    data: /home/victor/IdeaProjects/neatvue/public/projects


rabbitmq:
  input:
    exchange: user-queries-service
    queue: result
    routingKeys:
      status: status
      result: result
  output:
    exchange: experiment-server
    queue: experiment
    routingKeys:
      data: data
