server:
  port: 9000
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/neat
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      database-platform: org.hibernate.dialect.PostgreSQL11Dialect
# App Properties
app:
  jwt:
    Secret: SECRET
    Access_Expiration: 86400
    Refresh_Expiration: 2592000000
    Prefix: Bearer_
    Header: Authorization
  default:
    avatar: I:\Java Programs\IdeaProjects\neatvue\src\main\resources\static\assets\img\default-avatar.png

loger:
  level:
    root: DEBUG