server:
  port: 9000
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/neat
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  resources:
    static-locations: /home/victor/IdeaProjects/neatvue/public
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      database-platform: org.hibernate.dialect.PostgreSQL11Dialect
# App Properties
app:
  jwt:
    secret: SECRET
    access:
      expiration: 864000
      header: Authorization
      prefix: Bearer_
    refresh:
      expiration: 2592000000

loger:
  level:
    root: DEBUG


folders:
  avatar: ./public/avatar
