package ru.filippov.neat.entity;

public enum ExperimentStatus {
    NEW_EXPERIMENT,
    NORMALIZATION,
    NORMALIZED,
    NORMALIZATION_SERVICE_ERROR,
    SENDING_TO_NORMALIZATION_SERVICE_ERROR,
    IN_QUEUE,
    PREDICTION,
    PREDICTION_SERVICE_ERROR,
    SENDING_TO_PREDICTION_SERVICE_ERROR,
    PREDICTED,
    CREATING_REPORT,
    REPORT_SERVICE_ERROR,
    SENDING_TO_REPORT_SERVICE_ERROR,
    DONE,
}
